MedicineMonitoring/MedicineMonitoring/Controllers/MedicineController.cs
using MedicineMonitoring.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicineMonitoring.Controllers
{
    
    public class MedicineController : Controller
    {
        MedicineMonitoring.Methods.Methods methods = new MedicineMonitoring.Methods.Methods();
        // GET: Medicine
        MedicineDBContext _dbcontext = new MedicineDBContext();
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult MedList()
        {
            if (_dbcontext.Medicines.ToList().Count == 0)
            {
                ViewBag.msg = 1;
                return View();
            }
            else
            {
                return View(_dbcontext.Medicines.ToList());
            }
        }

        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult AddMedicine()
        {
            ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
            ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
            Medicine medicine = new Medicine();
            return View(medicine);
        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        [HttpPost]
        public ActionResult AddMedicine(Medicine medicine)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                var branch = _dbcontext.Branches.FirstOrDefault(x => x.BranchName == medicine.BranchAvaliable && x.BranchAddress == medicine.Address);

                if (branch != null)
                {
                    _dbcontext.Medicines.Add(medicine);
                    methods.Save(_dbcontext);
                    ViewBag.Message = "Medicine Details Added Succesfully";
                    return View();
                }
                else
                {
                    ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
                    ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
                   
                    ModelState.AddModelError("", "City is Mismatch with Branch");
                    return View();
                }
            }
        
        }

        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                var medicine = _dbcontext.Medicines.Where(x => x.MedId == id).FirstOrDefault();
                return View(medicine);
            }

            return View();

        }

        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult Edit(int? id)
        {
            Medicine medicine = null;
            if (id != null)
            {
                ViewBag.BrachList = _dbcontext.Branches.Select(x => x.BranchName);
                ViewBag.BranchAddress = _dbcontext.Branches.Select(x => x.BranchAddress);
                medicine = _dbcontext.Medicines.Where(x => x.MedId == id).FirstOrDefault();

            }

            return View(medicine);

        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        [HttpPost]
        public ActionResult Edit(Medicine medicine)
        {
            if (ModelState.IsValid)
            {

                _dbcontext.Entry(medicine).State = EntityState.Modified;
                methods.Save(_dbcontext);
                ViewBag.Message = "Medicine Details Updated Succesfully";
                return View();
            }
            return View();
        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult StockList()
        {
            if (_dbcontext.Medicines.ToList().Count == 0)
            {
                ViewBag.msg = 1;
                return View();
            }
            return View(_dbcontext.Medicines.ToList());
        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        public ActionResult EditStock(int? id)
        {
            Medicine medicine = null;
            if (id != null)
            {
                medicine = _dbcontext.Medicines.Where(x => x.MedId == id).FirstOrDefault();

            }

            return View(medicine);

        }
        [Authorize(Roles = "Admin,BranchAdmin")]
        [HttpPost]
        public ActionResult EditStock(Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                _dbcontext.Entry(medicine).State = EntityState.Modified;
                methods.Save(_dbcontext);
                ViewBag.Message = "Medicine Stock Details Updated Succesfully";
                return View();
            }
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult BranchStock()
        {

            return View(_dbcontext.Branches.ToList());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult ViewEachBranchStock(string id)
        {
            List<Medicine> stockList=new List<Medicine>();
            Branch branch = _dbcontext.Branches.FirstOrDefault(x => x.BranchId == id);
             stockList = _dbcontext.Medicines.Where(x => x.BranchAvaliable == branch.BranchName&&x.Address==branch.BranchAddress).ToList();
            var list = stockList.GroupBy(x => x.Disease).Select(Y => Y.FirstOrDefault()).ToList();
            
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult ViewEachBranchMedicine(int id)
        {
            Medicine medicine = _dbcontext.Medicines.FirstOrDefault(x => x.MedId == id);
            var stockList = _dbcontext.Medicines.Where(x => x.Disease==medicine.Disease&&x.BranchAvaliable==medicine.BranchAvaliable&&x.Address==medicine.Address).ToList();

            return View(stockList);
        }
    }
}

MedicineMonitoring/MedicineMonitoring/Views/Shared/_Footer.cshtml
<!-- footer-section start -->
<footer class="footer-section">
    <div class="footer-top pt-120 pb-120">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-8">
                    <div class="footer-widget widget-about">
                        <div class="widget-about-content">
                            <a href="#0" class="footer-logo"><img src="~/assets/images/plogo.jfif" alt="logo"width="60" height="30"></a>
                            <p> Best site to order your medicine without facing any difficulty </p>
                            <ul class="social-links">
                                <li><a href="#0"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#0"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#0"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#0"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-4">
                    <div class="footer-widget widget-menu">
                        <h4 class="widget-title">useful link</h4>
                        <ul>
                            <li><a href="#0">about</a></li>

                            <li><a href="#0">Home</a></li>
                            <li><a href="#0">Feedback</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-8">
                    <div class="footer-widget widget-address">
                        <h4 class="widget-title">contact with us</h4>
                        <ul>
                            <li>
                                <i class="fa fa-map-marker"></i>
                                <span>Indore, Madhya Pradesh, India</span>
                            </li>
                            <li>
                                <i class="fa fa-envelope"></i>
                                <span>www.medicinemonitorinfo2457@gmail.com www.oursupport/info@gmail.com</span>
                            </li>
                            <li>
                                <i class="fa fa-phone-square"></i>
                                <span>+91-014578541-09 , +91-85424-542-254 +91-47859-4541</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6">
                    
                </div>
                <div class="col-sm-6">
                    <ul class="payment-method d-flex justify-content-end">
                        <li>We accept</li>
                        <li><img src="~/assets/images/money-method/1.png" alt="image"></li>
                        <li><img src="~/assets/images/money-method/2.png" alt="image"></li>
                        <li><img src="~/assets/images/money-method/3.png" alt="image"></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer-section end -->
<!-- scroll-to-top start -->
<div class="scroll-to-top">
    <span class="scroll-icon">
        <i class="fa fa-rocket"></i>
    </span>
</div>
<!-- scroll-to-top end -->
<!-- jquery js link -->
<script src="~/assets/js/jquery-3.3.1.min.js"></script>
<!-- jquery migrate js link -->
<script src="~/assets/js/jquery-migrate-3.0.0.js"></script>
<!-- bootstrap js link -->
<script src="~/assets/js/bootstrap.min.js"></script>
<!-- lightcase js link -->
<script src="~/assets/js/lightcase.js"></script>
<!-- wow js link -->
<script src="~/assets/js/wow.min.js"></script>
<!-- nice select js link -->
<script src="~/assets/js/jquery.nice-select.min.js"></script>
<!-- datepicker js link -->
<script src="~/assets/js/datepicker.min.js"></script>
<script src="~/assets/js/datepicker.en.js"></script>
<!-- wickedpicker js link -->
<script src="~/assets/js/wickedpicker.min.js"></script>
<!-- owl carousel js link -->
<script src="~/assets/js/owl.carousel.min.js"></script>
<!-- jquery ui js link -->
<script src="~/assets/js/jquery-ui.min.js"></script>
<!-- main js link -->
<script src="~/assets/js/main.js"></script>

MedicineMonitoring/MedicineMonitoring/Views/Shared/_Header.cshtml
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Medicine Monitoring System</title>
    <!-- site favicon -->
    <link rel="shortcut icon" type="image/png" href="~/assets/images/favicon.jpg" />
    <!-- fontawesome css link -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.min.css">
    <!-- bootstrap css link -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <!-- lightcase css link -->
    <link rel="stylesheet" href="~/assets/css/lightcase.css">
    <!-- animate css link -->
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <!-- nice select css link -->
    <link rel="stylesheet" href="~/assets/css/nice-select.css">
    <!-- datepicker css link -->
    <link rel="stylesheet" href="~/assets/css/datepicker.min.css">
    <!-- wickedpicker css link -->
    <link rel="stylesheet" href="~/assets/css/wickedpicker.min.css">
    <!-- jquery ui css link -->
    <link rel="stylesheet" href="~/assets/css/jquery-ui.min.css">
    <!-- owl carousel css link -->
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <!-- main style css link -->
    <link rel="stylesheet" href="~/assets/css/main.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>



<!-- preloader start -->
<div id="preloader"></div>
<!-- preloader end -->
<!--  header-section start  -->
<header class="header-section" style="background-color:black">

    <div class="header-top">

        <div class="header-bottom">
            <div class="container">
                <nav class="navbar navbar-expand-lg p-0">
                    <a class="site-logo site-title" href="#0"><img src="~/assets/images/plogo.jfif" alt="site-logo" width="60" height="40"><span class="logo-icon"><i class="flaticon-fire"></i></span></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu-toggle"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav main-menu mr-auto">
                            @{ if (User.IsInRole("Admin"))
                                {
                                    <li>@Html.ActionLink("Home", "Home", "Admin")</li>
                                    <li class="menu_has_children">
                                        <a href="#0">Branch</a>
                                        <ul class="sub-menu">
                                            <li>@Html.ActionLink("Request", "Request", "Admin")</li>
                                            <li>@Html.ActionLink("Stock Information", "BranchStock", "Medicine")</li>
                                        </ul>
                                    </li>
                                    <li class="menu_has_children">
                                        <a href="#0">Medicine</a>
                                        <ul class="sub-menu">
                                            <li>@Html.ActionLink("Medicine Information", "MedList", "Medicine")</li>
                                            <li>@Html.ActionLink("Stock Information", "StockList", "Medicine")</li>
                                        </ul>
                                    </li>

                                    <li>@Html.ActionLink("LogOut", "Logout", "Account")</li>
                                }
                                else if (User.IsInRole("BranchAdmin"))
                                {
                                    <li>@Html.ActionLink("Home", "Home", "Admin")</li>
                                    <li>@Html.ActionLink("MedicineInformation", "MedList", "Medicine")</li>
                                    <li>@Html.ActionLink("MedicineStockInformation", "StockList", "Medicine")</li>
                                    <li>@Html.ActionLink("LogOut", "Logout", "Account")</li>
                                }
                                else if (User.IsInRole("Customer"))
                                {

                                    <li>@Html.ActionLink("MedicineSearch", "SearchMedicine", "Customer")</li>
                                    <li>@Html.ActionLink("LogOut", "Logout", "Account")</li>
                                }
                                else
                                {

                                    <li> @Html.ActionLink("Register", "Index", "Home") </li>
                                    <li> @Html.ActionLink("SignIn", "Login", "Account") </li>
                                } }
                        </ul>
                    </div>
                </nav>
            </div>
        </div><!-- header-bottom end -->
      </div>
</header>

MedicineMonitoring/MedicineMonitoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <title>@ViewBag.Title - Medicine Monitoring</title>
    

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
    
   
    <div class="container body-content">
        @RenderBody()
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>